set -g default-terminal "tmux-256color"
set -g extended-keys on
set -as terminal-features ",xterm-ghostty:RGB,clipboard,ccolour,cstyle,extkeys,focus,title"
set -as terminal-features ",xterm-256color:RGB"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r H resize-pane -L 5

bind h select-pane -L
bind l select-pane -R

bind j previous-window
bind k next-window

bind -r m resize-pane -Z

set -g mouse on
set-window-option -g mode-keys vi
bind y copy-mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
set -g set-clipboard on
set -sg escape-time 10

bind s display-popup -E -w 40% -h 40% -S "fg=#808080" -b rounded \
  "tmux list-sessions -F '#S' | fzf --reverse --border=none --margin=1 --padding=1 \
  --prompt='  ' --pointer='▌' --no-scrollbar \
  --color=bg:#1e1e1e,bg+:#323232,fg:#eeeeee,fg+:#eeeeee,hl:#fab283,hl+:#fab283,pointer:#fab283,prompt:#fab283,info:#808080 \
  | xargs -I{} tmux switch-client -t {}"

bind S command-prompt -p "New session name:" "new-session -s '%%'"

set -g status-style "bg=#1e1e1e,fg=#eeeeee"
set -g status-left-length 50
set -g status-left "#[fg=#eeeeee,bg=#323232] #S #[bg=#1e1e1e] "
set -g status-right "#[fg=#808080,bg=#1e1e1e] %H:%M "
set -g window-status-format "#[fg=#808080,bg=#1e1e1e] #I:#W "
set -g window-status-current-format "#[fg=#0a0a0a,bg=#fab283] #I:#W "
set -g pane-border-style "fg=#323232"
set -g pane-active-border-style "fg=#fab283"
set -g message-style "bg=#323232,fg=#eeeeee"
